In [121]:
import requests
import pandas as pd
from ast import literal_eval
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [106]:
DATA_PATH = r"raw_data/Relevant vs Irrelevant.xlsx"
df = pd.read_excel(DATA_PATH)
df.head(10)

_id  target  \
0  rfZFWnoByGgeg43IrgIr       1   
1  dQYh1HkBTz7BZCTC2Cmh       0   
2  EAYK1HkBTz7BZCTCIiBw       1   
3  lwV30nkBTz7BZCTCSAr_       1   
4  LAWH0nkBTz7BZCTCXhV7       1   
5  EgVf03kBTz7BZCTC3LsI       1   
6  kLXrW3kBTz7BZCTC5k_Q       1   
7  ErUQXHkBTz7BZCTC7Gpd       1   
8  HbUQXHkBTz7BZCTC7mqt       1   
9  orURXHkBTz7BZCTCB2ol       1   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

In [52]:
print(df.shape)
df.language.value_counts()

(3159, 13)


en    1541
es     342
fr     333
de     239
pt     227
nl     216
ru     137
ja      87
zh      35
lt       2
Name: language, dtype: int64

In [103]:
#text = "Le rapport fournit des recherches précises, des données de vente avec une analyse concernant les produits et les entreprises. Le rapport met l'accent sur les tendances et les idées ayant un impact sur l'industrie, couvrant la politique gouvernementale et l'innovation technologique. Le rapport couvre également le paysage concurrentiel et présente une vue holistique du marché. Demandez un exemple de copie du rapport – www.precisionreports.co/enquiry/request-sample/18353090 Le rapport Ingrédient Alimentaire Fonctionnel Marché a présenté des perspectives concurrentielles couvrant les mises à jour du marché mondial, la croissance future, les perspectives commerciales, les développements à venir et les investissements futurs. En outre, le rapport reconnaît les meilleures entreprises ainsi que leur stratégie marketing, leur profil d'entreprise, leurs dernières avancées, leur distribution commerciale, leurs portefeuilles de produits, leurs stratégies de marché, leur capacité et leur structure de coûts. En outre, une analyse concurrentielle en termes de divers paramètres tels que la concurrence directe, la concurrence indirecte, les forces et les faiblesses des principaux concurrents, le prix, les revenus, la marge brute, les entretiens, la répartition des affaires, les barrières à l'entrée et les fenêtres d'opportunité est fournie dans le rapport pour aider le consommateur à mieux connaître les concurrents. Le rapport présente également le paysage de la concurrence sur le marché et une analyse détaillée correspondante des principaux fournisseurs / fabricants du marché. Les principaux fabricants couverts dans ce rapport : Cargill Tate Lyle Nestle Arla Foods Amway Kerry Ingredion DSM Archer Daniels Midland Hearthside Food Solutions BASF Herbalife General Mills Pour comprendre comment l'impact de Covid-19 est couvert dans ce rapport – www.precisionreports.co/enquiry/request-covid19/18353090 Portée du rapport sur le Ingrédient Alimentaire Fonctionnel Marché : • Le mondial Ingrédient Alimentaire Fonctionnel marché est segmenté par entreprise, région (pays), par type et par application. Les joueurs, les parties prenantes et les autres participants du marché mondial du Ingrédient Alimentaire Fonctionnel pourront prendre le dessus en utilisant le rapport comme une ressource puissante. L'analyse segmentaire se concentre sur les ventes, les revenus et les prévisions par région (pays), par type et par application pour la période 2016-2027. • Cette étude de marché couvre le marché mondial et régional avec une analyse approfondie des perspectives de croissance globales du marché. En outre, il met en lumière le paysage concurrentiel complet du marché mondial. Le rapport offre en outre un aperçu du tableau de bord des principales entreprises englobant leurs stratégies marketing réussies, leur contribution au marché, les développements récents dans les contextes historiques et actuels. Renseignez-vous avant d'acheter ce rapport – www.precisionreports.co/enquiry/pre-order-enquiry/18353090 Sur la base des types, le Ingrédient Alimentaire Fonctionnel Marché est principalement divisé en : Vitamines Minéraux Prébiotiques Probiotiques Hydrocolloïdes Huiles Essentielles Acides Gras Oméga-3 Et 6 Caroténoïdes Sur la base des candidatures, le Ingrédient Alimentaire Fonctionnel Marché couvre : Boulangerie Et Céréales Les Produits Laitiers Viande, Poisson Et Œufs Des Produits À Base De Soja Autre Obtenez un exemple de copie du rapport sur le Ingrédient Alimentaire Fonctionnel Marché – www.precisionreports.co/enquiry/request-sample/18353090 Géographiquement, l'analyse détaillée de la consommation, des revenus, de la part de marché et du taux de croissance, l'historique et les prévisions des régions suivantes sont : Amérique du Nord • États Unis • Canada L'Europe • Allemagne • France • ROYAUME-UNI. • Italie • Russie Asie-Pacifique • Chine • Japon • Corée du Sud • Asie du sud est • Inde • Australie • Taïwan • Indonésie • Thaïlande • Malaisie l'Amérique latine • Mexique • Brésil • Argentine • Colombie Moyen-Orient et Afrique • Dinde • Arabie Saoudite • Émirats Arabes Unis Achetez ce rapport (Prix 3350 USD (Three Thousand Three Hundred Fifty USD) pour une licence mono-utilisateur) – www.precisionreports.co/purchase/18353090 Questions fréquemment posées Quelle est la portée du rapport? Cette étude de marché couvre le marché mondial et régional avec une analyse approfondie des perspectives de croissance globales du marché. En outre, il met en lumière le paysage concurrentiel complet du marché mondial. Le rapport offre en outre un aperçu du tableau de bord des principales entreprises englobant leurs stratégies marketing réussies, leur contribution au marché, les développements récents dans les contextes historiques et actuels. Quels sont les segments clés du marché ? • Par type de produit • Par utilisateur final/applications • Par technologie • Par région Quelle dynamique de marché affecte l'entreprise? Le rapport fournit une évaluation détaillée du marché en mettant en évidence des informations sur différents aspects qui incluent les moteurs, les contraintes, les opportunités et les menaces. Ces informations peuvent aider les parties prenantes à prendre les décisions appropriées avant d'investir. Points principaux du COT : 1 Ingrédient Alimentaire Fonctionnel Marché – Aperçu du rapport 2 Ingrédient Alimentaire Fonctionnel Marché – Production sur le marché mondial 3 Ingrédient Alimentaire Fonctionnel Marché – Ventes mondiales Ingrédient Alimentaire Fonctionnel 4 Ingrédient Alimentaire Fonctionnel Marché – Concurrence des fabricants Table des matières du mondial Ingrédient Alimentaire Fonctionnel marché @ www.precisionreports.co/TOC/18353090"
#translated = translate_w_deepl(text)
#print(translated['translations'][0]['text'])

### THIS PART IS NOW SUPPRESSED

'''
df['eng_title'] = str()
df['eng_desc'] = str()
df['eng_text'] = str()

for i,r in df.iterrows():
    print(i, r)
    print(r.title)

    if r.language == 'en':
        df.loc[i, "eng_title"] = r.title
        df.loc[i, "eng_desc"] = r.description
        df.loc[i, "eng_text"] = r.maintext
    else:
        print('title', r.title)#,'maintext']])
        print('description', r.description)  # ,'maintext']])
        df.loc[i, "eng_title"] = translate_w_deepl(r.title)
        df.loc[i, "eng_desc"] = translate_w_deepl(r.description)
        df.loc[i, "eng_text"] = translate_w_deepl(r.maintext)

'''
# @TODO: make this api work?
#from googletrans import Translator
#from google_trans_new import google_translator  
#translator = google_translator()
#text = 'Le rapport'
#print(translator.translate(text, lang_tgt='en')) #, dest='en', src='fr')


### get some credits to use DeepL API, mine for free version are already gone
### >>> using only english comments as I don't trust other translators as much (resucing our data by about one half)
df = df[df.language == 'en']
df.target.value_counts() #head(10)

0    1114
1     427
Name: target, dtype: int64

In [60]:
### we can keep just relevat data : lemma_* columns; I trust you guys. Is it a catch and I should do it on my own? 
# If I will have more time I will check it

df.head()

_id  target  \
1   dQYh1HkBTz7BZCTC2Cmh       0   
3   lwV30nkBTz7BZCTCSAr_       1   
5   EgVf03kBTz7BZCTC3LsI       1   
16  2bRAWnkBTz7BZCTCTjyv       0   
17  7LWUW3kBTz7BZCTCcBE9       0   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

# proposed steps
using mostly python's nltk library with scikit learn lib
<ol>
  <li>split data into train, validation, and test</li>
        <ol>
        <li>Train: fit the model</li>
        <li>Validation: evaluate fitness of interim models (created during iter process of comparing different M: classifiers and w different hyperparameters)</li>
        <li>Test: assess final model fitness</li>
        </ol>
  <li>Train and test</li>
        <ol>
        <li>Train is split using k-fold cross validation</li>
        </ol>
  <li>another yet unkonwn option.</li>
</ol>

In [199]:
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, accuracy_score


def clean_alt_list(list_):
    #list_ = list_.replace('\' ', ' ')
    list_ = list_.replace('[', '')
    list_ = list_.replace(']', '')
    return list_

DATA_PATH = r"raw_data/Relevant vs Irrelevant.xlsx"
df = pd.read_excel(DATA_PATH)
df = df[df.language == 'en']
# start simply with just title
#'''
sample = df[['target', 'lemma_title']]
sample['lemma_title'] = sample['lemma_title'].apply(literal_eval)
sample['lemma_title'] = [','.join(map(str, l)) for l in sample['lemma_title']]
#'''
'''
sample = df[['target', 'lemma_description']]
sample['lemma_description'] = sample['lemma_description'].apply(literal_eval)
sample['lemma_description'] = [','.join(map(str, l)) for l in sample['lemma_description']]
'''
'''
sample = df[['target', 'lemma_maintext']]
sample['lemma_maintext'] = sample['lemma_maintext'].apply(literal_eval)
#sample['lemma_maintext'] = sample['lemma_maintext'].apply(eval)
#sample['lemma_maintext'] = [','.join(l) for l in sample['lemma_maintext']]
#df['lemma_maintext'] = df['lemma_maintext'].apply(lambda x: ','.join(map(str, x)))
df['lemma_maintext'] = df['lemma_maintext'].agg(lambda x: ','.join(map(str, x)))
'''

#sample['lemma_title'] = sample['lemma_title'].apply(clean_alt_list)
sample.head()

C:\Users\Mirek\AppData\Local\Temp/ipykernel_4596/1117373127.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['lemma_title'] = sample['lemma_title'].apply(literal_eval)
C:\Users\Mirek\AppData\Local\Temp/ipykernel_4596/1117373127.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['lemma_title'] = [','.join(map(str, l)) for l in sample['lemma_title']]


target  \
1        0   
3        1   
5        1   
16       0   
17       0   

                                                                                                                                    lemma_title  
1                                                                                            microsoft,want,voting,trustworthy,partnership,help  
3                            insight,process,instrumentation,global,market,feature,honeywell,international,siemens,omron,researchandmarkets.com  
5   global,cloud,encryption,software,market,size,growth,trends,key,manufacturers,analysis-,gemalto,hpe,ibm,microsoft,symantec,thales,e,security  
16                                                        subsea,power,grid,system,market,anticipate,grow,cagr,term,revenue,forecast,period,arc  
17                                                   servicenow,launch,manufacturing,solutions,power,new,era,smart,manufacturing,marketscreener

In [238]:
X_train, X_test, y_train, y_test = train_test_split(sample['lemma_title'], sample['target'], test_size=0.4, random_state=666)
#X_train, X_test, y_train, y_test = train_test_split(sample['lemma_description'], sample['target'], test_size=0.3, random_state=666)
## check dist
print("train")
print(y_train.value_counts())
print("test")
print(y_test.value_counts())

train
0    657
1    267
Name: target, dtype: int64
test
0    457
1    160
Name: target, dtype: int64


some of the preprocessing was already done:
    tokenization
    normalization
    removing stop words
remaining steps
    count vectorise
    transformation to tf-idf representation

In [327]:
tfidf_vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 3))#analyzer=preprocess_text)#use_idf=True) 
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_train_tfidf.shape

(924, 16298)

In [328]:
sgd_clf = SGDClassifier(random_state=666)
sgf_clf_scores = cross_val_score(sgd_clf, X_train_tfidf, y_train, cv=5)
print(sgf_clf_scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (sgf_clf_scores.mean(), sgf_clf_scores.std() * 2))

[0.97837838 0.95675676 0.95135135 0.98378378 0.96195652]
Accuracy: 0.97 (+/- 0.03)


In [329]:
cross_val_score(sgd_clf, X_train_tfidf, y_train, cv=5, scoring='accuracy')

array([0.97837838, 0.95675676, 0.95135135, 0.98378378, 0.96195652])

In [330]:
sgf_clf_pred = cross_val_predict(sgd_clf, X_train_tfidf, y_train, cv=5)
print(confusion_matrix(y_train, sgf_clf_pred))

[[655   2]
 [ 29 238]]


In [326]:
grid = {'fit_intercept': [True,False],
        'early_stopping': [True, False],
        'loss' : ['hinge', 'log', 'squared_hinge'],
        'penalty' : ['l2', 'l1', 'none']
       }


search = GridSearchCV(estimator=sgd_clf, param_grid=grid, cv=5)
search.fit(X_train_tfidf, y_train)
search.best_params_

{'early_stopping': False,
 'fit_intercept': True,
 'loss': 'hinge',
 'penalty': 'l1'}

In [244]:
grid_sgd_clf_scores = cross_val_score(search.best_estimator_, X_train_tfidf, y_train, cv=5)
print(grid_sgd_clf_scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (grid_sgd_clf_scores.mean(), grid_sgd_clf_scores.std() * 2))

[0.98918919 0.98378378 0.98378378 0.99459459 0.98913043]
Accuracy: 0.99 (+/- 0.01)


In [246]:
pipe = Pipeline([('vectoriser', tfidf_vectorizer),
                 ('classifier', search.best_estimator_)])
pipe.fit(X_train, y_train)

Pipeline(steps=[('vectoriser', TfidfVectorizer()),
                ('classifier',
                 SGDClassifier(fit_intercept=False, loss='log', penalty='l1',
                               random_state=666))])

In [249]:
y_test_pred = pipe.predict(X_test)
print("Accuracy: %0.2f" % (accuracy_score(y_test, y_test_pred)))
print(confusion_matrix(y_test, y_test_pred))
print(metrics.classification_report(y_test, y_test_pred,
                                            target_names=['Positive', 'Negative']))

Accuracy: 0.99
[[454   3]
 [  4 156]]
              precision    recall  f1-score   support

    Positive       0.99      0.99      0.99       457
    Negative       0.98      0.97      0.98       160

    accuracy                           0.99       617
   macro avg       0.99      0.98      0.99       617
weighted avg       0.99      0.99      0.99       617



In [271]:
from time import time
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn import metrics

'''
grid = {'fit_intercept': [True,False],
        'early_stopping': [True, False],
        'loss' : ['hinge', 'log', 'squared_hinge'],
        'penalty' : ['l2', 'l1', 'none']}
search = GridSearchCV(estimator=sgd_clf, param_grid=grid, cv=5)
search.fit(X_train_tfidf, y_train)
search.best_params_
'''

t = time()
X_test_tfidf = tfidf_vectorizer.transform(X_test)
#gnb = GaussianNB()
gnb = MultinomialNB() ##better performance than GaussianNB()
y_pred = gnb.fit(X_train_tfidf.todense(), y_train).predict(X_test_tfidf.todense())

test_time = time() - t
print("test time:  %0.3fs" % test_time)

# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred,
                                            target_names=['Positive', 'Negative']))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

print('------------------------------')

#print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))

gnb.get_params()

grid_params = {'alpha': [0.01, 0.1, 0.3, 0.5, 0.75, 0.8, 0.85, 0.9, 1],
#        'class_prior': [True, False],
        'fit_prior' : [True,False]}

clf = GridSearchCV(gnb, grid_params, cv=5)
clf.fit(X_train_tfidf, y_train)

print("Best Score: ", clf.best_score_)
print("Best Params: ", clf.best_params_)

t = time()
gnb = MultinomialNB(alpha=0.8, fit_prior=True)
y_pred = gnb.fit(X_train_tfidf.todense(), y_train).predict(X_test_tfidf.todense())

test_time = time() - t
print("test time:  %0.3fs" % test_time)

# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred,
                                            target_names=['Positive', 'Negative']))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))



C:\Users\Mirek\Anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\Users\Mirek\Anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


test time:  0.042s
accuracy:   0.990
              precision    recall  f1-score   support

    Positive       0.99      0.99      0.99       457
    Negative       0.98      0.98      0.98       160

    accuracy                           0.99       617
   macro avg       0.99      0.99      0.99       617
weighted avg       0.99      0.99      0.99       617

confusion matrix:
[[454   3]
 [  3 157]]
------------------------------
Best Score:  0.9848413631022327
Best Params:  {'alpha': 0.8, 'fit_prior': True}
test time:  0.042s
accuracy:   0.990
              precision    recall  f1-score   support

    Positive       1.00      0.99      0.99       457
    Negative       0.98      0.99      0.98       160

    accuracy                           0.99       617
   macro avg       0.99      0.99      0.99       617
weighted avg       0.99      0.99      0.99       617

confusion matrix:
[[453   4]
 [  2 158]]


C:\Users\Mirek\Anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\Users\Mirek\Anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


In [283]:
from sklearn import svm
# SVM 
# Classifier - Algorithm - SVM
# fit the training dataset on the classifier
SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVM.fit(X_train_tfidf,y_train)
# predict the labels on validation dataset
predictions_SVM = SVM.predict(X_test_tfidf)
# Use accuracy_score function to get the accuracy
print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM, y_test)*100)

print(metrics.classification_report(y_test, predictions_SVM,
                                            target_names=['Positive', 'Negative']))

print(metrics.confusion_matrix(y_test, predictions_SVM))

print(SVM.get_params())

grid_params = {'C': [1, 10, 100], #1000], ## [0.01, 0.1, 0.3, 0.5, 0.75, 0.8, 0.85, 0.9, 1],
#        'class_prior': [True, False],
       'degree' : [2,3,4], ### just testing
       'kernel' : ['linear'], #, 'poly', 'rbf', 'sigmoid'], # , 'precomputed' removed due to "ValueError: X should be a square kernel matrix"
       'gamma' : ['scale', 'auto'],
       ##'shrinking' : [True,False],
       'probability' : [True,False],
       'verbose' : [True,False]
       #,'decision_function_shape' : ['ovo', 'ovr'] ### ignored for binary
       ##,'break_ties' : [True,False]
        }

t = time()
clf = GridSearchCV(SVM, grid_params, cv=5)
clf.fit(X_train_tfidf, y_train)
fine_tune_time = time() - t
print("fine tune time:  %0.3fs" % fine_tune_time) # 285.617s

print("Best Score: ", clf.best_score_)
print("Best Params: ", clf.best_params_) # {'C': 10, 'gamma': 'scale', 'kernel': 'linear', 'probability': True, 'shrinking': True, 'verbose': True}


SVM Accuracy Score ->  99.18962722852513
              precision    recall  f1-score   support

    Positive       0.99      1.00      0.99       457
    Negative       0.99      0.97      0.98       160

    accuracy                           0.99       617
   macro avg       0.99      0.99      0.99       617
weighted avg       0.99      0.99      0.99       617

[[456   1]
 [  4 156]]
{'C': 1.0, 'break_ties': False, 'cache_size': 200, 'class_weight': None, 'coef0': 0.0, 'decision_function_shape': 'ovr', 'degree': 3, 'gamma': 'auto', 'kernel': 'linear', 'max_iter': -1, 'probability': False, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}
[LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM

In [284]:
SVM = svm.SVC(C=10.0, kernel='linear', gamma='scale', degree=2, probability=True, shrinking=True, verbose=True)
SVM.fit(X_train_tfidf,y_train)
# predict the labels on validation dataset
predictions_SVM = SVM.predict(X_test_tfidf)
# Use accuracy_score function to get the accuracy
print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM, y_test)*100)

print(metrics.classification_report(y_test, predictions_SVM,
                                            target_names=['Positive', 'Negative']))

print(metrics.confusion_matrix(y_test, predictions_SVM))

[LibSVM]SVM Accuracy Score ->  99.18962722852513
              precision    recall  f1-score   support

    Positive       0.99      1.00      0.99       457
    Negative       0.99      0.98      0.98       160

    accuracy                           0.99       617
   macro avg       0.99      0.99      0.99       617
weighted avg       0.99      0.99      0.99       617

[[455   2]
 [  3 157]]


In [331]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix


rfc = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 666)

#SVM.fit(X_train_tfidf,y_train)
rfc.fit(X_train_tfidf, y_train)

predRF = rfc.predict(X_test_tfidf) 
#print(predRF[:10])

# Calculate the accuracy score
accuracy_RF = metrics.accuracy_score(y_test, predRF)
print(accuracy_RF)

Conf_metrics_RF = metrics.confusion_matrix(y_test, predRF)
print(Conf_metrics_RF)


print(metrics.classification_report(y_test, predRF,
                                            target_names=['Positive', 'Negative']))


param_grid = { 
    'n_estimators': [10, 200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
    }
t = time()
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(X_train_tfidf, y_train)

print("fine tuning time: ", time() - t)

print("Best Params: ", CV_rfc.best_params_)
# Best Params:  {'criterion': 'entropy', 'max_depth': 8, 'max_features': 'auto', 'n_estimators': 500}

ValueError: X has 3310 features, but RandomForestClassifier is expecting 16298 features as input.

In [304]:
rfc = RandomForestClassifier(n_estimators = 10, max_depth=20, max_features='auto', criterion = 'entropy', random_state = 42)

#SVM.fit(X_train_tfidf,y_train)
rfc.fit(X_train_tfidf, y_train)

predRF = rfc.predict(X_test_tfidf) 
#print(predRF[:10])

# Calculate the accuracy score
accuracy_RF = metrics.accuracy_score(y_test, predRF)
print(accuracy_RF)

Conf_metrics_RF = metrics.confusion_matrix(y_test, predRF)
print(Conf_metrics_RF)


print(metrics.classification_report(y_test, predRF,
                                            target_names=['Positive', 'Negative']))


0.9821717990275527
[[456   1]
 [ 10 150]]
              precision    recall  f1-score   support

    Positive       0.98      1.00      0.99       457
    Negative       0.99      0.94      0.96       160

    accuracy                           0.98       617
   macro avg       0.99      0.97      0.98       617
weighted avg       0.98      0.98      0.98       617



In [317]:
print(df.columns)
eval(df.loc[1,:]['lemma_maintext'])
#eval(df.loc[1,:]['lemma_title'])
#eval(df.loc[1,:]['lemma_description'])

Index(['_id', 'target', 'lemma_maintext', 'lemma_title', 'lemma_description',
       'description', 'language', 'maintext', 'title', 'url'],
      dtype='object')


['local',
 'school',
 'board',
 'state',
 'supreme',
 'court',
 'seat',
 'develop',
 'tech',
 'giant',
 'defend',
 'democracy',
 'project',
 'software',
 'design',
 'help',
 'election',
 'secure',
 'trustworthy',
 'electionguard',
 'new',
 'election',
 'software',
 'develop',
 'microsoft',
 '22defending',
 'democracy%22',
 'project',
 'microsoft',
 'electionguard',
 'new',
 'election',
 'software',
 'develop',
 'microsoft',
 'defend',
 'democracy',
 'project',
 'year',
 'later',
 'widespread',
 'distrust',
 'discord',
 'surround',
 'presidential',
 'election',
 'help',
 'case',
 'kind',
 'technology',
 'loading',
 'load',
 'error',
 'think',
 'important',
 'time',
 'history',
 'vendor',
 'try',
 'build',
 'technology',
 'system',
 'ability',
 'build',
 'trust',
 'electoral',
 'process',
 'tom',
 'burt',
 'microsoft',
 'corporate',
 'vice',
 'president',
 'customer',
 'security',
 'trust',
 'tell',
 'cnn',
 'business',
 'microsoft',
 'thursday',
 'announce',
 'implementation',
 'electio